### ISSUE TITLE
Trending page rendering problem

### ISSUE THREAD

**Issue by LHaosss** [FlareZone/FlareZone#117]
### Describe the bug

re-Rending page componment upon clicking Trending.
page componment rendering should only occur on first entry or refresh.

### Reproduction

rendering

### System Info

```Shell
no
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jokereven** [comment]
have use swr to replace fetch, problem resolve, thanks.
